# This pipeline shows how to:
# - Provision an Azure VM and register the VM in an Azure Pipelines environment.
# - Run a task like InstallNetCoreRuntimeAndHosting on the provisioned VM.
# - Remove the used Azure Pipelines environment and provisioned Azure resource group.
#
# The following variables need to be provided to the pipeline:
# - token           : a Personal Access Token with the scopes 'Environment (Read & manage)' and 'Tokens (Read & manage)'.
# - adminPassword   : a password for the admin user of the virtual machine.
#
# This pipeline also expects an Azure (Resource Manager) service connection in Azure DevOps with the name 'Azure Visual Studio Enterprise'.


trigger: none
pr: none

pool:
  name: easec-pool
  
variables:
  resourceGroupName: "snapshot-rg"
  virtualMachineName: "easec-vm"

stages:
- stage: Provision
  jobs:
  - job:
    steps:
     - task: AzureCLI@2
       inputs:
         azureSubscription: 'AzureServiceConnection'
         scriptType: pscore
         scriptLocation: inlineScript
         inlineScript: |
          az vm stop --name $(virtualMachineName) --resource-group $(resourceGroupName) --no-wait
          Write-Host "VM $(virtualMachineName) in Resource Group $(resourceGroupName) has been stopped."
          az vm deallocate --name $(virtualMachineName) --resource-group $(resourceGroupName)
          Write-Host "VM $(virtualMachineName) in Resource Group $(resourceGroupName) has been deallocated."
          az vm delete --name $(virtualMachineName) --resource-group $(resourceGroupName) --yes --force-deletion
          Write-Host "VM $(virtualMachineName) in Resource Group $(resourceGroupName) has been deleted."  