# This pipeline will delete all resources in Resource Group defined in the variable resourceGroupName.

#
# The following variables need to be provided to the pipeline:
# - resourceGroupName            : name for the Resource Group where the vm will be created.
# - virtualMachineName           : name for the virtual machine.
#
# This pipeline also expects an Azure (Resource Manager) service connection in Azure DevOps with the name 'AzureServiceConnection'.


trigger: none
pr: none

pool:
  name: easec-pool
  
variables:
  resourceGroupName: "snapshot-rg"
  virtualMachineName: "easec-vm"

stages:
- stage: Provision
  jobs:
  - job:
    steps:
     - task: AzureCLI@2
       inputs:
         azureSubscription: 'AzureServiceConnection'
         scriptType: pscore
         scriptLocation: inlineScript
         inlineScript: |
          az vm stop --name $(virtualMachineName) --resource-group $(resourceGroupName) --no-wait
          Write-Host "VM $(virtualMachineName) in Resource Group $(resourceGroupName) has been stopped."
          az vm deallocate --name $(virtualMachineName) --resource-group $(resourceGroupName)
          Write-Host "VM $(virtualMachineName) in Resource Group $(resourceGroupName) has been deallocated."
          az resource list --resource-group "snapshot-rg" 
              | ConvertFrom-Json
                  | Foreach-Object {az resource delete --resource-group "snapshot-rg" --ids $_.id --verbose}
          az network public-ip delete --resource-group "snapshot-rg" --name easec-vmPublicIP
          az network vnet delete --resource-group "snapshot-rg" --name easec-vmVNET
          az network nsg delete --resource-group "snapshot-rg" --name easec-vmNSG
