# This pipeline will delete all resources in Resource Group defined in the variable resourceGroupName.

#
# The following variables need to be provided to the pipeline:
# - resourceGroupName            : name for the Resource Group where the vm will be created.
# - virtualMachineName           : name for the virtual machine.
#
# This pipeline also expects an Azure (Resource Manager) service connection in Azure DevOps with the name 'AzureServiceConnection'.


trigger: none
pr: none

pool:
  name: easec-pool
  
variables:
  resourceGroupName: "snapshot-rg"
  virtualMachineName: "easec-vm"

stages:
- stage: Provision
  jobs:
  - job:
    steps:
     - task: AzureCLI@2
       inputs:
         azureSubscription: 'AzureServiceConnection'
         scriptType: pscore
         scriptLocation: inlineScript
         inlineScript: |
          az vm delete --resource-group "$(resourceGroupName)" --name $(virtualMachineName) --yes --force-deletion y
          az disk delete --name "easec-vm_OsDisk_1_man" --resource-group "$(resourceGroupName)" --yes
          az disk delete --name "easec-vm_DataDisk_1_man" --resource-group "$(resourceGroupName)" --yes
          az disk delete --name "easec-vm_DataDisk_0_snap" --resource-group "$(resourceGroupName)" --yes
          az disk delete --name "easec-vm_OsDisk_1_snap" --resource-group "$(resourceGroupName)" --yes
          $vmNic = az vm nic list --resource-group "$(resourceGroupName)" --vm-name $(virtualMachineName)
          Write-Host "NIC: $vmNic"
          az network nic ip-config update --name ipconfigeasec-vm --resource-group "$(resourceGroupName)" --nic-name easec-vmVMNic --public-ip-address null
          az network public-ip delete --resource-group "$(resourceGroupName)" --name easec-vmPublicIP
          az network nic delete --resource-group "$(resourceGroupName)" --name "easec-vmVMNic"
          az network nsg delete --resource-group "$(resourceGroupName)" --name easec-vmNSG
          az network vnet delete --resource-group "$(resourceGroupName)" --name easec-vmVNET
          az resource list --resource-group "$(resourceGroupName)" 
              | ConvertFrom-Json
                  | Foreach-Object {az resource delete --resource-group "$(resourceGroupName)" --ids $_.id --verbose}
